server:
  port: 8080

spring:
  application:
    name: crud-practice
  datasource:
    url: "jdbc:mysql://localhost:3306/crud_practice"
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



